title: Blockinfo.de
description: ""
url: "https://blockinfo.de" # the base hostname & protocol for your site, e.g. http://example.com
url_http: "http://blockinfo.de"
twitter_username: Blockinfo_DE
github_username: blockchain-info
envelope_username: info@blockinfo.de
ga_property: "UA-102954545-1"
permalink: /article/:slug/
repository_url: "https://github.com/blockchain-info/blockinfo.de"
twitter_url: https://twitter.com
ws_course_id: 17
custom_search_id: "011221661346354572919:zpf1hzv67my"

languages: ["de", "en"]

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: "_i18n/de/_posts" # an empty string here means all files in the project
    values:
      layout: "post"
  - scope:
      path: "_i18n/en/_posts" # an empty string here means all files in the project
    values:
      layout: "post"
  - scope:
      path: "_pages" # an empty string here means all files in the project
    values:
      layout: "page"

pagination:
  enabled: true
  per_page: 5
  permalink: '/seite/:num/'
  title: ':title - Seite :num von :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
sass:
  style: :compressed
  sass_dir: assets/css
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-contentblocks
  - jekyll-multiple-languages-plugin
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - .gitignore
  - nginx.conf
